sudo: required
dist: trusty
language: python
python:
  - "3.6"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  ssh_known_hosts: ladders.lrem.net
before_install:
  - "export DISPLAY=:99.0"
  - - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid \
      --make-pidfile --background --exec /usr/bin/Xvfb -- \
      :99 -ac -screen 0 3840x2160x24"
  - "sh -e /etc/init.d/xvfb start"
  - if [[ $TRAVIS_BRANCH = "master" ]] &&
       [[ $TRAVIS_PULL_REQUEST = "false" ]] &&
       [[ $TRAVIS_REPO_SLUG = "lrem/ladders" ]]; then
      export PROD=1;
    fi
  - nvm install node
install:
  - pip install -r requirements.txt
  - cd web
  - nvm use node
  - npm install -g @angular/cli
  - npm install
  - cd ..
script:
  - mypy --ignore-missing-imports api.py
  - pylint api.py
  - python3 api.py &
  - cd web
  - ng build
  - ng lint
  - ng serve &
  - sleep 5 # In the odd case starting the server takes longer than Chrome.
  - ng e2e
  - if [ $PROD ]; then ng build -prod -e prod; fi
after_success:
  - if [ $PROD ]; then 
    git config --global user.email "builds@travis-ci.com";
    git config --global user.name "Travis CI";
    git checkout -b "build-${TRAVIS_BUILD_NUMBER}";
    git add -f dist/;
    git commit -m "Artifacts from Travis build ${TRAVIS_BUILD_NUMBER}.";
    git push --force https://prod:${PROD_PWD}@ladders.lrem.net/git/ladders;
    fi
after_failure:
  - rsync -av screenshots dev@ladders.lrem.net:${TRAVIS_BUILD_NUMBER}
  - for f in screenshots/*; do
      curl -F "file=@$f;filename=${TRAVIS_BUILD_NUMBER}-$(basename $f)" http://prod:${PROD_PWD}@ladders.lrem.net/dev/;
      done