sudo: required
dist: trusty
language: python
python:
  - "3.6"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - if [[ $TRAVIS_BRANCH = "master" ]] &&
       [[ $TRAVIS_PULL_REQUEST = "false" ]] &&
       [[ $TRAVIS_REPO_SLUG = "lrem/ladders" ]]; then
      export PROD=1;
    fi
  - nvm install node
install:
  - pip install -r requirements.txt
  - cd web
  - nvm use node
  - npm install -g @angular/cli
  - npm install
  - cd ..
script:
  - mypy --ignore-missing-imports api.py
  - python3 api.py &
  - cd web
  - ng build
  - ng lint
  - ng serve -prod &
  - sleep 5 # In the odd case starting server takes longer than Chrome.
  - ng e2e
  - if [ $PROD ]; then ng build -prod -e prod; fi
after_success:
    #- export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  #- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  #- git push origin $GIT_TAG
  - if [ $PROD ]; then 
    git config --global user.email "builds@travis-ci.com";
    git config --global user.name "Travis CI";
    git checkout -b "build-${TRAVIS_BUILD_NUMBER}";
    git add -f dist/;
    git commit -m "Artifacts from Travis build ${TRAVIS_BUILD_NUMBER}.";
    git push https://prod:${PROD_PWD}@ladders.lrem.net/git/ladders;
    fi
